# antigen
source ~/.jangho/apps/zsh/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle zsh-users/zsh-syntax-highlighting

antigen theme agnoster

antigen apply

# path
PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"

# avoid dangers
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'

# taskwarrior
alias t='task'

# update
alias update='~/.jangho/updateall.sh'

# ssh
alias mango='mosh --ssh="ssh -p 50022" jangho@my.jangho.kr'
alias martini='mosh janghose@martini.snucse.org'

# strong pwgen
alias spwgen='pwgen -y -1 40 5'

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# exit status
alias x='echo $?'

# host-specific settings
[ -r ~/.jangho/hosts/$(hostname)/zsh/zshrc_host ] && source ~/.jangho/hosts/$(hostname)/zsh/zshrc_host

# okay to go
true
