# zgen
source ~/.jangho/apps/zsh/zgen/zgen.zsh

if ! zgen saved; then
    echo "Creating a zgen save"

    zgen oh-my-zsh
    zgen oh-my-zsh plugins/git
    zgen load zsh-users/zsh-syntax-highlighting
    zgen oh-my-zsh themes/agnoster

    zgen save
fi

# path
PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"

# avoid dangers
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'

# taskwarrior
alias t='task'
alias tt='task etc'
alias tw='task away'
alias ta='task active'
alias ts='task sync'
alias tm='task minimal -class'

# update
alias update='[ -f ~/.jangho-system/updateall.sh ] && ~/.jangho-system/updateall.sh; ~/.jangho/updateall.sh'

# ssh
alias mango='mosh --ssh="ssh -p 50022" jangho@my.jangho.kr'
alias martini='mosh janghose@martini.snucse.org'

# strong pwgen
alias spwgen='pwgen -y -1 40 5'

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# exit status
alias x='echo $?'

# nocolor
alias nocolor=' sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"'

# host-specific settings
[ -r ~/.jangho/hosts/$(hostname)/zsh/zshrc_host ] && source ~/.jangho/hosts/$(hostname)/zsh/zshrc_host

# okay to go
true
